Updated preferences api
googlecodelabs/android-datastore pull request #6
Opened 2020-08-26 00:20 UTC by rohitsat13

Changes here:
1) Used the new context.createDataStore() factory function
2) Created the new preferences keys and moved them into a private object in UserPreferencesRepository
3) Used the new map like Preferences API
4) Also removed the extension functions to keep it streamlined.

Tested by using the locally built preferences and running the app on my phone.

2020-08-28 16:01 UTC, florina-muntenescu commented on app/src/main/java/com/codelab/android/datastore/data/UserPreferencesRepository.kt
> +import androidx.datastore.preferences.*
don't use * imports (disable this in AS)

2020-08-28 16:03 UTC, florina-muntenescu requested changes

2020-08-28 16:03 UTC, florina-muntenescu commented on app/src/main/java/com/codelab/android/datastore/data/UserPreferencesRepository.kt
> +            name = USER_PREFERENCES_NAME,
keep the migration comment above

2020-08-28 16:03 UTC, florina-muntenescu commented on app/src/main/java/com/codelab/android/datastore/data/UserPreferencesRepository.kt
> +    private object Keys {
rename to `PreferencesKeys`

2020-08-28 16:03 UTC, florina-muntenescu commented on app/src/main/java/com/codelab/android/datastore/data/UserPreferencesRepository.kt
> +}
add new line at the end of the file

2020-08-31 07:36 UTC, manuelvicnt approved these changes

2020-08-31 07:39 UTC, manuelvicnt commented on app/src/main/java/com/codelab/android/datastore/data/UserPreferencesRepository.kt
> +                    preferences[PreferencesKeys.SORT_ORDER] ?: SortOrder.NONE.name)
Nit: this parenthesis should be in a new line. Same above in line 100

2020-08-31 08:24 UTC, merged